

battle_phrases = [
    ' takes one in the eye!',
    ' trips and eats dirt!',
    ' hurt themself in their confusion.',
    ' slipped on Piranhahead\'s viscous drippings...',
    ' ate a knuckle sandwich!',
    ' blocked with their face.',
    ' was knocked down.',
    ' received an 80\'s Greatest Hit.',
    ' was slapped in the face.',
    ' was kicked in the Ligma Bells.',
    ' was barely scratched.',
    ' was stabbed in the stomach.',
    ' was shot.',
    ' was hit with an arrow.',
    ' took an arrow to the knee!',
    ' takes it right on the chin.',
    ' gets bashed in the skull.',
    ' gets hit with a rock.',
    ' gets poked with a sharp stick.',
    ' gets hit with an audience member\'s shoe.',
    ' takes a hit to the face.',
    ' was verbally abused by the enemy.',
    ' gets mauled by Ted the warbear.',
    ' gets pummeled with a Ten Sided Mace.',
    ' gets shot by a Glitter Spitter.',
    ' shook the Eight Ball of Misfortune and exploded!',
    ' tried to \"plug in\" Light-Up Hitch and was electrocuted!',
    ' was run over by the Hero Hauler!',
    ' was run over by the Zap Mobile!',
    ' was bitten by the enemy\'s pet Gorblin and bled out.',
    ' was impaled and bled out.',
    ' choked on the enemy\'s Two Silver Ligma Bells.',
    ' gets stabbed.',
    ' gets sliced.',
    ' gets hugged by Hurkenstein.',
    ' was taken by surprise.',
    '\'s reaction time was too slow.',
    ' miscalculated their swing.',
    ' fell on their sword.',
    ' dipped when they should have ducked!',
    ' barely felt it.',
    ' slipped on Kendalf\'s Soapy Staff residue.',
    ' was distracted by Barb-Ra\'s beauty and tripped on a rock.',
    ' was burned and returned!',
    ' was hit by Kendalf\'s stray spell!',
    ' looked too juicy and got mauled by Ted!',
    ' stepped on Rose\'s thorn!',
    ', while pondering the meaning of life, was knocked out.',
    ' was ambushed.',
    ' disgraced their God and accepted judgement.',
    ' drank a mysterious potion.',
    ' is starting to feel those nachos.'

]